/* One entry per activity. The hub page, the route folders and the page metadata
   all read from here, so adding or renaming one starts in this file.

   `kind` and `cta` exist because only one of these five is actually a game.
   Labelling a breathing exercise "Play Game" sets the wrong expectation before
   someone has even clicked, so each card says what it really is and its button
   names the thing you will be doing. */
export const GAMES = [
  {
    slug: "balloon-breath",
    kind: "Breathing exercise",
    cta: "Take a Breath",
    name: "Balloon Breath",
    tone: "teal",
    blurb: "Hold to fill the balloon. Let go, and it floats away with your breath.",
    tagline: "Five slow breaths, paced by your own hand.",
  },
  {
    slug: "sound-garden",
    kind: "Music activity",
    cta: "Make Some Music",
    name: "Sound Garden",
    tone: "sky",
    blurb: "Tap squares to plant notes. They loop back as a tune that cannot sound wrong.",
    tagline: "Build a calm little melody, one tap at a time.",
  },
  {
    slug: "zen-sand-garden",
    kind: "Quiet activity",
    cta: "Rake the Sand",
    name: "Zen Sand Garden",
    tone: "sun",
    blurb: "Rake patterns into the sand with your finger and set stones wherever you like.",
    tagline: "No goal and no ending — just sand, stones and your hand.",
  },
  {
    slug: "mandala-maker",
    kind: "Creative activity",
    cta: "Be Creative",
    name: "Mandala Maker",
    tone: "grape",
    blurb: "Draw one line and it mirrors eight ways. Every scribble comes out beautiful.",
    tagline: "Symmetry does the hard part. You just draw.",
  },
  {
    slug: "pop-it",
    kind: "Fidget",
    cta: "Start Popping",
    name: "Pop It",
    tone: "coral",
    blurb: "A whole board of bubbles to press. When you finish it, flip it over and go again.",
    tagline: "Something to do with your hands, endlessly.",
  },
  {
    slug: "ripple-pond",
    kind: "Quiet activity",
    cta: "Touch the Water",
    name: "Ripple Pond",
    tone: "sky",
    blurb: "Touch the water and rings spread out. The lilies and the fish feel every one.",
    tagline: "Still water, and whatever you do to it.",
  },
  {
    slug: "how-am-i-feeling",
    kind: "Feelings",
    cta: "Build a Face",
    name: "How Am I Feeling?",
    tone: "sun",
    blurb: "Change the eyebrows, eyes and mouth until the face matches you. It'll tell you the word.",
    tagline: "Putting a name to it, without having to explain.",
  },
  {
    slug: "kind-words",
    kind: "Creative activity",
    cta: "Make a Sentence",
    name: "Kind Words",
    tone: "grape",
    blurb: "Word tiles you can arrange into a sentence. Every word here is a gentle one.",
    tagline: "Fridge magnets, but nothing unkind in the box.",
  },
  {
    slug: "balance-stones",
    kind: "Quiet activity",
    cta: "Stack the Stones",
    name: "Balance Stones",
    tone: "teal",
    blurb: "Set one smooth stone on another and see how high the pile will go.",
    tagline: "Only the stone you just placed can ever fall.",
  },
  {
    slug: "colour-mixer",
    kind: "Creative activity",
    cta: "Mix Some Colours",
    name: "Colour Mixer",
    tone: "coral",
    blurb: "Drop paints into the bowl and watch a brand new colour appear. It'll tell you its name.",
    tagline: "No wrong mixes — every one of them gets a name.",
  },
  {
    slug: "constellation-connect",
    kind: "Quiet activity",
    cta: "Join the Stars",
    name: "Constellation Connect",
    tone: "grape",
    blurb: "Join the stars into any shape you like, then give it a name of your own.",
    tagline: "A sky with no correct answer in it.",
  },
  {
    slug: "calm-catch",
    kind: "Game",
    cta: "Play the Game",
    name: "Calm Catch",
    tone: "coral",
    blurb: "Move a basket to gather kindness, hope and joy as they drift down.",
    tagline: "A slow, unhurried catching game. One minute long.",
  },
];
